mod advanced_metadata;
mod appearance;
mod application;
mod archive_executor;
mod archive_ui;
mod batch_rename;
mod bookmarks;
mod browser;
mod checksum_executor;
mod checksum_ui;
mod cli_routing;
mod clipboard;
mod command_palette;
mod command_registry;
mod completeness;
mod content_search;
mod context_menu;
pub mod copy_executor;
pub mod create_executor;
mod custom_actions;
pub mod devices;
mod drag_drop;
mod duplicate_finder;
mod duplicate_hash_cache;
mod duplicate_ui;
mod file_watcher;
mod filename_search;
mod fingerprint_store;
mod folder_filter;
pub mod guardrail_controller;
pub mod guardrail_policy_worker;
pub mod guardrail_preflight;
pub mod guardrail_store;
pub mod guardrail_ui;
pub mod guardrail_ui_model;
mod iconography;
mod inspector;
mod integration;
mod integrity;
mod integrity_executor;
mod integrity_monitor;
mod integrity_monitor_store;
mod integrity_ui;
mod integrity_watch;
pub mod job_manager;
mod keybindings;
mod keyboard_shortcuts;
mod launcher;
mod location_completion;
mod location_input;
mod locations;
mod metadata;
mod miller_detail;
mod miller_view;
pub mod move_executor;
mod operation_control;
mod operation_recovery;
mod operations;
#[cfg(test)]
mod performance;
mod permanent_delete_executor;
mod permission_executor;
mod preferences;
pub mod preview;
mod privileged_access;
mod privileged_operations;
mod properties;
#[cfg(test)]
mod release_metadata;
pub mod restore_executor;
mod search_index;
mod selection_slice;
mod session_store;
mod settings_center;
mod sort_metadata_index;
pub mod state;
mod storage;
mod system_thumbnailer;
mod templates;
mod terminal;
mod terminal_ui;
mod thumbnail;
mod thumbnail_cache;
pub mod trash_executor;
mod ui;
pub mod verified_copy_executor;
pub mod verified_usb;
mod view;
mod vim_mode;
mod worker;

fn main() -> gtk::glib::ExitCode {
    application::run()
}
